#!/usr/bin/env bash
# Ce script modifie le fichier /etc/hosts pour changer les résolutions de localhost et facebook.com

# Sauvegarde de l'état actuel de /etc/hosts
cp /etc/hosts /etc/hosts.bak

# Modification du fichier hosts
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
